In [4]:
import pandas as pd
import numpy as np
ds= pd.Series([10,20,30,40])
print(ds)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
ss= pd.Series((10,20,30,40))
print(ss)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
qs= pd.Series([10,20,30,40],index=['A', 'B', 'C', 'D'])
print(qs)

A    10
B    20
C    30
D    40
dtype: int64

In [8]:
s1= pd.Series({'V':10,'H':20,'A':30})
print(s1)

V    10
H    20
A    30
dtype: int64

In [9]:
s2= pd.Series(range(1,10))
print(s2)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [24]:
import numpy as np
s3= pd.Series(np.array([1,2,3,45]))
print(s3)

0     1
1     2
2     3
3    45
dtype: int32

In [14]:
ds = pd.DataFrame([['V','H','A'],[10,20,30],[1,2,3]], index=['A','B','C'])
print(ds)

    0   1   2
A   V   H   A
B  10  20  30
C   1   2   3

In [15]:
ds = pd.DataFrame({'p':['V','H','A'],'q':[10,20,30],'r':[1,2,3]}, index=['A','B','C'])
print(ds)

   p   q  r
A  V  10  1
B  H  20  2
C  A  30  3

In [18]:
ds = pd.DataFrame({'p':['V','H','A'],'q':[10,20,30],'r':[1,2,3]}, index=['A','B','C'], columns =['x','y','z'])

print(ds)

     x    y    z
A  NaN  NaN  NaN
B  NaN  NaN  NaN
C  NaN  NaN  NaN

In [22]:
ds= pd.DataFrame(np.array([[1,2,3],[4,5,6]]))
print(ds)

   0  1  2
0  1  2  3
1  4  5  6

In [23]:
ds = pd.DataFrame([{'name':'abcd','Fb':20}, {'name':'bcda','Fb':30}], index=['o','p'])
print(ds)

   name  Fb
o  abcd  20
p  bcda  30

In [78]:
df= pd.DataFrame([['Python',"VHA",100],["FSD","PSP",200],["COA","DPS",300]],columns=['Sub','Fac','Marks'])
print(df)

      Sub  Fac  Marks
0  Python  VHA    100
1     FSD  PSP    200
2     COA  DPS    300

In [76]:
df.set_index('Sub')

        Fac Marks
Sub
Python  FSD   COA
VHA     PSP   DPS
100     200   300

In [79]:
df.set_index('Sub',drop=False)

           Sub  Fac  Marks
Sub
Python  Python  VHA    100
FSD        FSD  PSP    200
COA        COA  DPS    300

In [81]:
df= pd.DataFrame([['Python',"VHA",100],["FSD","PSP",200],["COA","DPS",300]],columns=['Sub','Fac','Marks'])
print(df)

      Sub  Fac  Marks
0  Python  VHA    100
1     FSD  PSP    200
2     COA  DPS    300

In [82]:
df= df.reset_index()
print(df)

   index     Sub  Fac  Marks
0      0  Python  VHA    100
1      1     FSD  PSP    200
2      2     COA  DPS    300

In [136]:
df= pd.DataFrame([['Python',"VHA",100],["FSD","PSP",200],["COA","DPS",300],['TOC','VBY',400]],columns=['Sub','Fac','Marks'])
print(df)

      Sub  Fac  Marks
0  Python  VHA    100
1     FSD  PSP    200
2     COA  DPS    300
3     TOC  VBY    400

In [137]:
df=df.set_index('Sub')
print(df)

        Fac  Marks
Sub
Python  VHA    100
FSD     PSP    200
COA     DPS    300
TOC     VBY    400

In [140]:
df.loc['FSD','Fac']

'PSP'

In [144]:
df.loc['FSD','Marks']=500
print(df)

        Fac  Marks
Sub
Python  VHA    100
FSD     NAS    500
COA     DPS    300
TOC     VBY    400

In [146]:
df.loc['Project']=['VHA',10]

In [147]:
df['HOD']='MJT'

In [148]:
print(df)

         Fac  Marks  HOD
Sub
Python   VHA    100  MJT
FSD      NAS    500  MJT
COA      DPS    300  MJT
TOC      VBY    400  MJT
Project  VHA     10  MJT

In [180]:
f= np.random.randint(1,100,(8,5))
df=pd.DataFrame(f,columns=['A','B','C','D','E'])

In [181]:
print(df)

    A   B   C   D   E
0  53  97  97  31  46
1  82  35  12  52  58
2   2  87  89  73  73
3  10  43  16  59  37
4  92   3  11  87   5
5  25  13  75  58  91
6  28  47  80   3  32
7  16  19  46  20  24

In [182]:
df.shape

(8, 5)

In [183]:
df.size

40

In [184]:
df.ndim

2

In [185]:
df['Sum']=df['A']+df['B']+df['C']+df['D']+df['E']

In [186]:
print(df)

    A   B   C   D   E  Sum
0  53  97  97  31  46  324
1  82  35  12  52  58  239
2   2  87  89  73  73  324
3  10  43  16  59  37  165
4  92   3  11  87   5  198
5  25  13  75  58  91  262
6  28  47  80   3  32  190
7  16  19  46  20  24  125

In [189]:
df.iloc[5,2]=81
df

    A   B   C   D   E  Sum
0  53  97  97  31  46  324
1  82  35  12  52  58  239
2   2  87  89  73  73  324
3  10  43  16  59  37  165
4  92   3  11  87   5  198
5  25  13  81  58  91  262
6  28  47  80   3  32  190
7  16  19  46  20  24  125

In [195]:
df.loc[2:8,'B':'E']

    B   C   D   E
2  87  89  73  73
3  43  16  59  37
4   3  11  87   5
5  13  81  58  91
6  47  80   3  32
7  19  46  20  24

In [197]:
df.loc['8']=[10,20,30,40,50,150]

In [198]:
print(df)

    A   B   C   D   E  Sum
0  53  97  97  31  46  324
1  82  35  12  52  58  239
2   2  87  89  73  73  324
3  10  43  16  59  37  165
4  92   3  11  87   5  198
5  25  13  81  58  91  262
6  28  47  80   3  32  190
7  16  19  46  20  24  125
8  10  20  30  40  50  150

In [199]:
f= np.random.randint(1,100,(5,4))

In [200]:
df=pd.DataFrame(f,columns=['CourseID','CourseName','Credits','Faculty'])

In [201]:
df.set_index('CourseID')

          CourseName  Credits  Faculty
CourseID
59                75       63       93
28                53       49       12
24                35       74       20
76                92       31       79
18                66       82       50

In [202]:
df['Semester']=1

In [203]:
print(df)

   CourseID  CourseName  Credits  Faculty  Semester
0        59          75       63       93         1
1        28          53       49       12         1
2        24          35       74       20         1
3        76          92       31       79         1
4        18          66       82       50         1

In [204]:
df.iloc[1,2]=100

In [205]:
print(df)

   CourseID  CourseName  Credits  Faculty  Semester
0        59          75       63       93         1
1        28          53      100       12         1
2        24          35       74       20         1
3        76          92       31       79         1
4        18          66       82       50         1

In [217]:
df
df.loc[6]=[22,21,22,23,1,22]

In [218]:
print(df)

   CourseID  CourseName  Credits  Faculty  Semester   6
0        59          75       63       93         1  20
1        28          53      100       12         1  21
2        24          35       74       20         1  22
3        76          92       31       79         1  23
4        18          66       82       50         1   1
6        22          21       22       23         1  22

In [215]:
df.head()

   CourseID  CourseName  Credits  Faculty  Semester   6
0        59          75       63       93         1  20
1        28          53      100       12         1  21
2        24          35       74       20         1  22
3        76          92       31       79         1  23
4        18          66       82       50         1   1

In [216]:
df.tail()

   CourseID  CourseName  Credits  Faculty  Semester   6
0        59          75       63       93         1  20
1        28          53      100       12         1  21
2        24          35       74       20         1  22
3        76          92       31       79         1  23
4        18          66       82       50         1   1