In [1]:
import pandas as pd
import numpy as np

In [3]:
df1= pd.DataFrame({"A":[1,2], "B":[3,4]})
df2= pd.DataFrame({"A":[5,6], "B":[7,8]})

In [4]:
df1

   A  B
0  1  3
1  2  4

In [5]:
df2

   A  B
0  5  7
1  6  8

In [8]:
pd.concat((df1,df2),ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [9]:
pd.concat((df1,df2), axis=0, keys=["df1", "df2"])

       A  B
df1 0  1  3
    1  2  4
df2 0  5  7
    1  6  8

In [10]:
df1= pd.DataFrame({"A":[1,2], "B":[3,4]})
df2= pd.DataFrame({"C":[5,6], "B":[7,8]})

In [11]:
df1

   A  B
0  1  3
1  2  4

In [12]:
df2

   C  B
0  5  7
1  6  8

In [13]:
pd.concat((df1,df2))

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [14]:
pd.concat((df1,df2),axis=1,sort=True)

   A  B  C  B
0  1  3  5  7
1  2  4  6  8

In [15]:
df1= pd.DataFrame({"A":[1,2], "B":[3,4]})
df2= pd.DataFrame({"C":[5,6], "B":[7,8]})

In [19]:
pd.concat((df1,df2), join="outer")

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [20]:
df1= pd.DataFrame({"A":[1,2], "B":[3,4]})
df2= pd.DataFrame({"C":[5,6], "B":[7,8]})

In [21]:
pd.concat((df1,df2),sort ="True")

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [22]:
pd.concat((df1,df2),sort ="False")

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [26]:
df1= pd.DataFrame({"name":["vha", "psp","mss","vby","dps"],
                  "sub":["python","fsd","coa","dm","toc"], 
                  "id":[3,2,1,4,6]})

In [27]:
df2=pd.DataFrame({"id":[1,2,3,4,5], "mark":[9,8,10,8,8]})

In [28]:
df1

  name     sub  id
0  vha  python   3
1  psp     fsd   2
2  mss     coa   1
3  vby      dm   4
4  dps     toc   6

In [29]:
df2

   id  mark
0   1     9
1   2     8
2   3    10
3   4     8
4   5     8

In [32]:
pd.merge(df1,df2,on="id")

  name     sub  id  mark
0  vha  python   3    10
1  psp     fsd   2     8
2  mss     coa   1     9
3  vby      dm   4     8

In [33]:
pd.merge(df1,df2,on="id", how="outer")

  name     sub  id  mark
0  vha  python   3  10.0
1  psp     fsd   2   8.0
2  mss     coa   1   9.0
3  vby      dm   4   8.0
4  dps     toc   6   NaN
5  NaN     NaN   5   8.0

In [34]:
pd.merge(df1,df2,on="id",how="left")

  name     sub  id  mark
0  vha  python   3  10.0
1  psp     fsd   2   8.0
2  mss     coa   1   9.0
3  vby      dm   4   8.0
4  dps     toc   6   NaN

In [36]:
pd.merge(df1,df2,on="id",how="cross")

MergeError: Can not pass on, right_on, left_on or set right_index=True or left_index=True

In [39]:
pd.merge(df1,df2,left_index=True, right_index=True, suffixes=("_df1", "_df2"))

  name     sub  id_df1  id_df2  mark
0  vha  python       3       1     9
1  psp     fsd       2       2     8
2  mss     coa       1       3    10
3  vby      dm       4       4     8
4  dps     toc       6       5     8

In [40]:
df1= pd.DataFrame({"name":["vha", "psp","mss","vby","dps"],
                  "sub":["python","fsd","coa","dm","toc"], 
                  "id":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5], "mark":[9,8,10,8,8],"fac":["vha","nas", "vby", "mss","dps"]})

In [41]:
pd.merge(df1,df2,left_on="name", right_on="fac", how="outer",suffixes=("_b1_sem3" ,"_b1_sem4"))

  name     sub  id_b1_sem3  id_b1_sem4  mark  fac
0  vha  python         3.0         1.0   9.0  vha
1  psp     fsd         2.0         NaN   NaN  NaN
2  mss     coa         1.0         4.0   8.0  mss
3  vby      dm         4.0         3.0  10.0  vby
4  dps     toc         6.0         5.0   8.0  dps
5  NaN     NaN         NaN         2.0   8.0  nas